### ISSUE TITLE
Stuck on "Connecting...  Authentication proxy started"

### ISSUE THREAD

**Issue by FedericoHeichou** [lensapp/lens#2189]
**Describe the bug**
After a update (I think to 4.1.0, now I use 4.1.1) when I open Lens it stucks on "Connecting...  Authentication proxy started". I've never seen this message before because I didn't configured http proxy. To unstuck this "Proxy Authentication" I need to click on the "+" icon "Add cluster", then click back to my cluster. I can bypass this proxy authentication opening preferences and closing them too.
I tried to delete the AppData/Roaming/Lens directory, but I have still this problem

**Environment (please complete the following information):**
- Lens Version: 4.1.1
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): Github 4.0.0 then automatically updated each version

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: ­ƒÜÇ Starting Lens from "C:\Users\federico.heichou\AppData\Roaming\Lens"
info: ­ƒÉÜ Syncing shell environment
info: ­ƒÆ¥ Loading stores
info: [STORE]: LOADED from C:\Users\federico.heichou\AppData\Roaming\Lens\config.json
info: [STORE]: LOADED from C:\Users\federico.heichou\AppData\Roaming\Lens\lens-cluster-store.json
info: [STORE]: LOADED from C:\Users\federico.heichou\AppData\Roaming\Lens\lens-workspace-store.json
info: [STORE]: LOADED from C:\Users\federico.heichou\AppData\Roaming\Lens\lens-extensions.json
info: [STORE]: LOADED from C:\Users\federico.heichou\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json
info: ­ƒöæ Getting free port for LensProxy server
debug: Lookup new free port..
debug: New port found: 56333
info: [CLUSTER-MANAGER]: init cluster {"id":"72d00a22-51de-4842-8934-85e0518b9503","name":"heichou","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
debug: Lookup new free port..
info: ­ƒöî Starting LensProxy
info: [LENS-PROXY]: Proxy server has started at http://localhost:56333
info: ­ƒöÄ Testing LensProxy connection ...
debug: New port found: 56334
debug: Dumping KubeConfig: {"apiVersion":"v1","kind":"Config","preferences":{},"current-context":"heichou","clusters":[{"name":"heichou","cluster":{"server":"http://127.0.0.1:56333/72d00a22-51de-4842-8934-85e0518b9503"}}],"contexts":[{"name":"heichou","context":{"cluster":"heichou","user":"proxy","namespace":"heichou"}}],"users":[{"name":"proxy","user":{}}]}
debug: Created temp kubeconfig "heichou" at "C:\Users\FEDERI~1.HEI\AppData\Local\Temp\kubeconfig-72d00a22-51de-4842-8934-85e0518b9503":
apiVersion: v1
kind: Config
preferences: {}
current-context: heichou
clusters:
  - name: heichou
    cluster:
      server: 'http://127.0.0.1:56333/72d00a22-51de-4842-8934-85e0518b9503'
contexts:
  - name: heichou
    context:
      cluster: heichou
      user: proxy
      namespace: heichou
users:
  - name: proxy
    user: {}

info: [CLUSTER]: "heichou" init success {"id":"72d00a22-51de-4842-8934-85e0518b9503","context":"heichou","apiUrl":"https://192.168.x.x:6443"}
info: ÔÜí LensProxy connection OK
debug: [EXTENSIONS-LOADER]: load on main
info: ­ƒûÑ´©Å  Starting WindowManager
info: ­ƒº® Initializing extensions
info: [EXTENSION-DISCOVERY] loading extensions from C:\Users\federico.heichou\AppData\Roaming\Lens
debug: [EXTENSION-DISCOVERY]: 7 extensions loaded {"folderPath":"C:\\Users\\federico.heichou\\AppData\\Local\\Programs\\kontena-lens\\resources\\extensions","extensions":[{"id":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\kube-object-event-status\\package.json","absolutePath":"C:\\Users\\federico.heichou\\AppData\\Local\\Programs\\kontena-lens\\resources\\extensions\\kube-object-event-status","manifestPath":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\kube-object-event-status\\package.json","manifest":{"name":"kube-object-event-status","version":"0.1.0","description":"Adds kube object status from events","renderer":"dist/renderer.js","lens":{"metadata":{},"styles":[]},"scripts":{"build":"webpack --config webpack.config.js","dev":"npm run build --watch","test":"echo NO TESTS"},"dependencies":{},"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","ts-loader":"^8.0.4","typescript":"^4.0.3","webpack":"^4.44.2","mobx":"^5.15.5","react":"^16.13.1"}},"isBundled":true,"isEnabled":true},{"id":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\lens-license\\package.json","absolutePath":"C:\\Users\\federico.heichou\\AppData\\Local\\Programs\\kontena-lens\\resources\\extensions\\license-menu-item","manifestPath":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\lens-license\\package.json","manifest":{"name":"lens-license","version":"0.1.0","description":"License menu item","main":"dist/main.js","scripts":{"build":"webpack -p","dev":"webpack --watch","test":"jest --passWithNoTests --env=jsdom src $@"},"dependencies":{},"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","@types/webpack":"^4.41.17","jest":"^26.6.3","mobx":"^5.15.5","react":"^16.13.1","ts-loader":"^8.0.4","ts-node":"^9.0.0","typescript":"^4.0.3","webpack":"^4.44.2"}},"isBundled":true,"isEnabled":true},{"id":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\lens-metrics-cluster-feature\\package.json","absolutePath":"C:\\Users\\federico.heichou\\AppData\\Local\\Programs\\kontena-lens\\resources\\extensions\\metrics-cluster-feature","manifestPath":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\lens-metrics-cluster-feature\\package.json","manifest":{"name":"lens-metrics-cluster-feature","version":"0.1.0","description":"Lens metrics cluster feature","renderer":"dist/renderer.js","lens":{"metadata":{},"styles":[]},"scripts":{"build":"webpack --config webpack.config.js","dev":"npm run build --watch","test":"jest --passWithNoTests --env=jsdom src $@"},"dependencies":{},"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","jest":"^26.6.3","mobx":"^5.15.5","react":"^16.13.1","semver":"^7.3.2","ts-loader":"^8.0.4","typescript":"^4.0.3","webpack":"^4.44.2"}},"isBundled":true,"isEnabled":true},{"id":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\lens-node-menu\\package.json","absolutePath":"C:\\Users\\federico.heichou\\AppData\\Local\\Programs\\kontena-lens\\resources\\extensions\\node-menu","manifestPath":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\lens-node-menu\\package.json","manifest":{"name":"lens-node-menu","version":"0.1.0","description":"Lens node menu","renderer":"dist/renderer.js","lens":{"metadata":{},"styles":[]},"scripts":{"build":"webpack --config webpack.config.js","dev":"npm run build --watch","test":"jest --passWithNoTests --env=jsdom src $@"},"dependencies":{},"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","jest":"^26.6.3","mobx":"^5.15.5","react":"^16.13.1","ts-loader":"^8.0.4","typescript":"^4.0.3","webpack":"^4.44.2"}},"isBundled":true,"isEnabled":true},{"id":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\lens-pod-menu\\package.json","absolutePath":"C:\\Users\\federico.heichou\\AppData\\Local\\Programs\\kontena-lens\\resources\\extensions\\pod-menu","manifestPath":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\lens-pod-menu\\package.json","manifest":{"name":"lens-pod-menu","version":"0.1.0","description":"Lens pod menu","renderer":"dist/renderer.js","lens":{"metadata":{},"styles":[]},"scripts":{"build":"webpack --config webpack.config.js","dev":"npm run build --watch","test":"jest --passWithNoTests --env=jsdom src $@"},"dependencies":{},"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","jest":"^26.6.3","mobx":"^5.15.5","react":"^16.13.1","ts-loader":"^8.0.4","typescript":"^4.0.3","webpack":"^4.44.2"}},"isBundled":true,"isEnabled":true},{"id":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\lens-survey\\package.json","absolutePath":"C:\\Users\\federico.heichou\\AppData\\Local\\Programs\\kontena-lens\\resources\\extensions\\survey","manifestPath":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\lens-survey\\package.json","manifest":{"name":"lens-survey","version":"0.1.0","description":"Lens survey","main":"dist/main.js","renderer":"dist/renderer.js","lens":{"metadata":{},"styles":[]},"scripts":{"build":"webpack -p","dev":"webpack --watch","test":"jest --passWithNoTests --env=jsdom src $@"},"dependencies":{},"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","got":"^11.8.1","jest":"^26.6.3","node-machine-id":"^1.1.12","react":"^16.13.1","refiner-js":"^1.0.1","ts-loader":"^8.0.4","typescript":"^4.0.3","webpack":"^4.44.2"}},"isBundled":true,"isEnabled":true},{"id":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\lens-telemetry\\package.json","absolutePath":"C:\\Users\\federico.heichou\\AppData\\Local\\Programs\\kontena-lens\\resources\\extensions\\telemetry","manifestPath":"C:\\Users\\federico.heichou\\AppData\\Roaming\\Lens\\node_modules\\lens-telemetry\\package.json","manifest":{"name":"lens-telemetry","version":"0.1.0","description":"Lens telemetry","main":"dist/main.js","renderer":"dist/renderer.js","lens":{"metadata":{},"styles":[]},"scripts":{"build":"webpack -p","dev":"webpack --watch","test":"jest --passWithNoTests --env=jsdom src $@"},"dependencies":{},"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","@types/analytics-node":"^3.1.3","analytics-node":"^3.4.0-beta.3","jest":"^26.6.3","mobx":"^5.15.5","node-machine-id":"^1.1.12","react":"^16.13.1","ts-loader":"^8.0.4","typescript":"^4.0.3","universal-analytics":"^0.4.23","webpack":"^4.44.2"}},"isBundled":true,"isEnabled":true}]}
info: [EXTENSION-INSTALLER] installing dependencies at C:\Users\federico.heichou\AppData\Roaming\Lens
info: [WINDOW-MANAGER]:┬áLoading Main window from url: http://localhost:56333 ...
info: [EXTENSION-INSTALLER] dependencies installed at C:\Users\federico.heichou\AppData\Roaming\Lens
debug: [EXTENSION-DISCOVERY]: 0 extensions loaded {"folderPath":"C:\\Users\\federico.heichou\\.k8slens\\extensions","extensions":[]}
info: [EXTENSION-DISCOVERY] watching extension add/remove in C:\Users\federico.heichou\.k8slens\extensions
info: [EXTENSION]: enabled lens-license@0.1.0
info: [STORE]: LOADED from C:\Users\federico.heichou\AppData\Roaming\Lens\extension-store\lens-survey\preferences-store.json
info: [EXTENSION]: enabled lens-survey@0.1.0
telemetry main extension activated
info: [STORE]: LOADED from C:\Users\federico.heichou\AppData\Roaming\Lens\extension-store\lens-telemetry\preferences-store.json
info: [EXTENSION]: enabled lens-telemetry@0.1.0
info: [CLUSTER]: activate {"id":"72d00a22-51de-4842-8934-85e0518b9503","name":"heichou","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: bind events {"id":"72d00a22-51de-4842-8934-85e0518b9503","name":"heichou","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: reconnect {"id":"72d00a22-51de-4842-8934-85e0518b9503","name":"heichou","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
debug: Set kubectl version 1.18.15 for cluster version 1.18.15 using version map
debug: Acquired a lock for 1.18.15
info: [WINDOW-MANAGER]: Main window loaded
info: ­ƒôí Checking for app updates
info: Checking for update
debug: Releasing lock for 1.18.15
debug: spawning kubectl proxy with args: proxy,-p,56334,--kubeconfig,C:\Users\federico.heichou\.kube\config,--context,heichou,--accept-hosts,192.168.x.x,--reject-paths,^[^/]
info: [KUBE-AUTH]: out-channel "kube-auth:72d00a22-51de-4842-8934-85e0518b9503" {"data":"Authentication proxy started\n","meta":{"id":"72d00a22-51de-4842-8934-85e0518b9503","name":"heichou","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}
debug: Set kubectl version 1.20.2 for cluster version v1.20.2 using version map
debug: Acquired a lock for 1.20.2
debug: Local kubectl is version 1.20.2
debug: Releasing lock for 1.20.2
info: Update for version 4.1.1 is not available (latest version: 4.1.1, downgrade is disallowed).
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
info: using helm as prometheus provider
(node:1528) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

# Wait some seconds
info: [CLUSTER]: refresh {"id":"72d00a22-51de-4842-8934-85e0518b9503","name":"heichou","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
info: [CLUSTER]: refresh {"id":"72d00a22-51de-4842-8934-85e0518b9503","name":"heichou","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}

# Clicking Add Cluster and go back
info: [STORE]: SAVING C:\Users\federico.heichou\AppData\Roaming\Lens\lens-cluster-store.json
info: [STORE]: SAVING C:\Users\federico.heichou\AppData\Roaming\Lens\lens-workspace-store.json
info: [STORE]: SAVING C:\Users\federico.heichou\AppData\Roaming\Lens\lens-cluster-store.json
info: [STORE]: SAVING C:\Users\federico.heichou\AppData\Roaming\Lens\lens-workspace-store.json

# Clicking preferences and go back
info: [MENU]: navigating to /preferences

(node:1528) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

# Closing
info: APP:QUIT
info: [CLUSTER]: disconnect {"id":"72d00a22-51de-4842-8934-85e0518b9503","name":"heichou","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
info: [CLUSTER]: unbind events {"id":"72d00a22-51de-4842-8934-85e0518b9503","name":"heichou","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
```

**Comment by odhekar** [comment]
I am facing this problem and confirmed the workaround just now.

**Comment by FedericoHeichou** [comment]
It has been fixed with 4.1.2
`Fix an issue where a cluster gets stuck on "Connecting ..." phase`

Just tested and it works

**Comment by tjipz8** [comment]
still happening on 4.1.2
from debug 

Error occurred in handler for 'cluster:activate': Error: timeout
    at Timeout.timeoutFunc (C:\Users\ttham\AppData\Local\Programs\Lens\resources\app.asar\node_modules\tcp-port-used\index.js:204:25)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by FedericoHeichou** [comment]
Ok I reopen this issue for who has still problems

**Comment by jim-docker** [comment]
@tjipz8, your problem sounds a little different, can you open separate issue with more details if possible?

**Comment by tjipz8** [comment]
doesn't happen anymore, not sure what happen

**Comment by FedericoHeichou** [comment]
Ok I close this issue

**Comment by edTheGuy00** [comment]
@tjipz8 did you restart your computer? It happens to me quite often after a while I just get `http: proxy error: dial tcp: i/o timeout` 

Qutting and reopening doesn't work either, I have to restart my entire computer for it to work again. 

I'm on v 4.1.3 on macOS 11.1

**Comment by syedaliammar** [comment]
I had to restart Lens and it worked like a charm.

**Comment by K4leri** [comment]
reopening this problem. the same issue now. I have never use proxy but get

<html>
<body>

INFO | Starting connection ...
-- | --
INFO | Authentication proxy started
INFO | Refreshing connection status ...
ERROR | E1010 18:08:20.670557 23960 proxy_server.go:147] Error while proxying request: getting credentials: exec: fork/exec C:\Users\...\yc.exe: Access is denied.
ERROR | Failed to GET "https://..."


</body>
</html>
