### ISSUE TITLE
No metrics for a node's pods listing

### ISSUE THREAD

**Issue by oliverbarnes** [lensapp/lens#2903]
**Describe the bug**

We've installed lens-metrics prometheus sucessfully on a Linoke k8s cluster through the settings pane on Lens 4.2.4 / Mac, and we're able to see metrics on the nodes listing views and individual pods. 

Which is already very useful and gives me enough visibility to troubleshoot issues I'm currently facing. The 1-click solution is much appreciated, thanks for that 🙏 

The one thing we're missing is seeing relative metrics for pods in a node (screenshot below)

**To Reproduce**

Assuming a working Lens install with a running cluster:

1 - ctrl-click the cluster icon
2 - select settings
3 - click Install on lens-metrics section
4 - go to the Nodes view > click on a node and scroll down to Pods

**Expected behavior**

Pods should have metrics shown for them

**Screenshots**

<img width="662" alt="Screen Shot 2021-05-28 at 8 26 35 PM" src="https://user-images.githubusercontent.com/21290/120028249-57228800-bfec-11eb-9798-5c13d62ad90f.png">

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- OS: MacOS 11.3.1 (20E241)
- Installation method: image from github
- Cluster: LKE
- K8s version: 1.19

**Comment by brandoncollins7** [comment]
I am having the same issue for quite a while now:

![image](https://user-images.githubusercontent.com/36413482/120032952-f0d83e00-bfc8-11eb-8fd1-f20ae371f11f.png)

All other metric look fine.

**Comment by jim-docker** [comment]
I believe this is fixed in #2744, for v4.2.5

**Comment by jdato** [comment]
I still have the issue in Lens 5.

Lens: 5.1.3-latest.20210722.1
Electron: 9.4.4
Chrome: 83.0.4103.122
Node: 12.14.1

MacOS BigSur
V 11.4

![image](https://user-images.githubusercontent.com/22294144/127104594-9f2509be-1ba0-4a21-b7d7-72f7ab25b532.png)

**Comment by agrondemiraj** [comment]
This issue is still present. It is present for over a year and I have been keeping Lens up to date always hoping that this will be fixed on the latest releases.

My Lens details below
![1733306663616860169746091721413](https://github.com/user-attachments/assets/9a49951a-dd20-4124-a7ba-57d0a123f104)

I also cannot see the CPU and Memory stats of Pods when selecting Node as below:
![17333068496945247478026679610271](https://github.com/user-attachments/assets/d489ab2f-93cc-4ecc-9cdf-9cf8f44fc3fe)
