### ISSUE TITLE
Unusable in version 5

### ISSUE THREAD

**Issue by magnusja** [lensapp/lens#3271]
Log window (if it works) always puts me to the top instead of bottom when data is (re)loaded (thats at least how it seems...)

Usually for logs I am just getting the infinite spinner and if not the spinner screen just turns gray ...
![image](https://user-images.githubusercontent.com/1659457/124495805-dad44f00-ddb8-11eb-9524-8a04610dc067.png)

Unfortunately, unusable this was a really good app a year ago but last months with each release only going downhill you really should put some more effort into your QA.

I am on archlinux

**Comment by guillaumelachaud** [comment]
I am on macOS, and to me the logs icon on pods is completely gone.

**Comment by slayerjain** [comment]
@GuillaumeLachaud same with me :(

**Comment by sbesselsen** [comment]
Same with me, and the shell command is also gone. Looks like a bunch of plugins are not getting loaded.

**Comment by derekperkins** [comment]
Most of the plugins are erroring for me on 5.0.1 on Big Sur 11.4

**Comment by aleksfront** [comment]
@GuillaumeLachaud @slayerjain Missing logs icons in pods are unrelated issue, but it is already fixed and available in Lens v5.0.2.

**Comment by magnusja** [comment]
So I still have this scrolling issue, also on a mac. Do I need to do sth so that it follows, anything else than clicking this `Jump to bottom` button?

Also what about this gray screen? How can I get back w/o restarting?

<img width="2314" alt="Screenshot 2021-07-07 at 13 05 04" src="https://user-images.githubusercontent.com/1659457/124748923-f314ad00-df23-11eb-96ec-6c50f0ee26cf.png">

**Comment by magnusja** [comment]
Scrolling issue: https://nc.jahnen.me/s/aJH6sXng3aE4Ryp

Seems that at the very end it suddenly works ...
