### ISSUE TITLE
Auto Refresh Pods information not working

### ISSUE THREAD

**Issue by Edwarrdo** [lensapp/lens#555]
Since latest 1 or 2 version updates the auto-refresh isn't working anymore and you have to manually refresh to see if the pod is initialized or not. Please fix this fast. It was perfect before

**Comment by jakolehm** [comment]
Does this happen with v3.5.1?

**Comment by Edwarrdo** [comment]
yes, I just updated to 3.5.1 and it still happens

**Comment by jakolehm** [comment]
@Edwarrdo could you provide as much info as possible from your environment/cluster.

**Comment by ThorstenLuebbers** [comment]
@jakolehm  I have the same issue since Lens Version 3.5.0. Running on Windows 10 (Version 2004, OS Build 190041.329). Kubectl version output:
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Is there any other information I could provide?

**Comment by UnleashSpirit** [comment]
Hello,
I have the same kind of thing.
When I destroy a pod, deployment restart it automaticaly but I have to switch menu and come back to "Pods" to see it restarting. It's just interface's refresh, pod still restart instantly

Lens v3.5.1
Windows 10

**Comment by jdomag** [comment]
I have the same on fedora with Lens 4,0,4 -  and it's not about pods only, but jobs, deployments etc.

**Comment by mih-kopylov** [comment]
I have the same behaviour with Lens 4.1.4 on Windows 10. 
It's very annoying to switch to another tab and to Pods back and forth.
@jakolehm is it possible to prioritise this bug?

**Comment by Nokel81** [comment]
Do you have `watch` permissions for those resources?

**Comment by mih-kopylov** [comment]
@Nokel81 I think so. And there're no error messages in console

**Comment by Nokel81** [comment]
what is the output of `kubectl auth can-i watch pods --namespace <namespace>`? Can you run Lens in debug mode from the console and post some of those logs?

**Comment by mih-kopylov** [comment]
@Nokel81 here you are:
```
> kubectl auth can-i watch pods --namespace load
yes

> kubectl auth can-i watch deployments --namespace load
yes
```

Could you please advise how can I run Lens in debug mode?

**Comment by Nokel81** [comment]
`DEBUG=true ./path/to/lens/binary`

**Comment by Nokel81** [comment]
Edit: what distro of kube are you using. What OS are you using?

**Comment by mih-kopylov** [comment]
@Nokel81 I'm using Windows OS
```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19041 N/A Build 19041
```
And the latest Lens
![image](https://user-images.githubusercontent.com/6898003/112416569-fc905580-8d36-11eb-864f-ea4b080a0616.png)


And work with clusters of 2 versions:
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

> kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

I've set `DEBUG` env variable to `true` and restarted the Lens app, but there're no much logs appeared.
```
>echo %DEBUG%
true
```
[lens1.log](https://github.com/lensapp/lens/files/6201926/lens1.log)
[lens.log](https://github.com/lensapp/lens/files/6201927/lens.log)

There's also an error message in console, which doesn't appear in logs. I suppose the message is because I don't have Prometheus installed in my clusters.
![image](https://user-images.githubusercontent.com/6898003/112416165-2eed8300-8d36-11eb-8557-80e6354c16c5.png)

When I restart a deployment, I see the pods state in early beginning, they don't update
![image](https://user-images.githubusercontent.com/6898003/112416378-a02d3600-8d36-11eb-9c59-ff8e6ce81afb.png)

Another notice: Age column gets updated only when I scroll list of pods.

**Comment by Nokel81** [comment]
When you restarted lens did you quit the tray icon too? Lens won't pick up new env vars unless you do that.

**Comment by mih-kopylov** [comment]
@Nokel81 yes, sure. I've clicked Quit App tray menu item.
Right now I've just repeated that once again, but nothing changed

[lens1.log](https://github.com/lensapp/lens/files/6209614/lens1.log)
[lens.log](https://github.com/lensapp/lens/files/6209615/lens.log)

**Comment by mih-kopylov** [comment]
@Nokel81 Hey!
I've upgraded to 4.2.0, but see the same experience.
Here're some new logs, with DEBUG=true enabled - they have some debug messages as well. 

[lens1.log](https://github.com/lensapp/lens/files/6265149/lens1.log)
[lens.log](https://github.com/lensapp/lens/files/6265151/lens.log)

Could you please take a look at the bug? It's very annoying.

**Comment by pblim** [comment]
Any workaround for this issue?

**Comment by mih-kopylov** [comment]
I've noticed an interesting thing.
I've spinned up a local k8s cluster, and my Lens updates pods status as expected. So it seems somehow related to my cloud k8s clusters. If @Nokel81 or anyone else has some ideas what to check - please welcome

**Comment by Nokel81** [comment]
Seems slightly related to https://github.com/lensapp/lens/issues/3821

**Comment by rerime** [comment]
Same story
```
Lens: 5.4.6-latest.20220428.1
Electron: 14.2.4
Chrome: 93.0.4577.82
Node: 14.17.0
```

**Comment by Nokel81** [comment]
@rerime can you try the latest beta?

**Comment by mobilesfinks** [comment]
@mih-kopylov  ` some ideas what to check - please welcome` 
we have same problem. 
We migrate our service to another cluster (flant/deckhouse) and now we have problem with refresh view (command+R help)
Before we use cluster configured by kubeadm and all works fine. 

If Lens use web-sockets i think problem can be at that point.  

```
Lens: 5.4.6-latest.20220428.1
Electron: 14.2.4
Chrome: 93.0.4577.82
Node: 14.17.0

Kubernetes CLuster v1.21.11
Deckhouse version v1.32.7 FE
```

**Comment by rerime** [comment]
Problem exists.

**Comment by mobilesfinks** [comment]
@Nokel81 latest Beta help, now all refresh online
```
Lens: 5.5.0-beta.1.20220513.1
Electron: 14.2.9
Chrome: 93.0.4577.82
Node: 14.17.0

```

**Comment by Nokel81** [comment]
@mobilesfinks So the fixes that are in that beta have helped?

**Comment by rerime** [comment]
Ok, will wait stable release.

**Comment by jim-docker** [comment]
Assuming this is fixed, please let us know if otherwise

**Comment by lghinet** [comment]
hello, 
it is not fixed, 
it works only if you filter pods by namespace, or when the list is very small, 
but when you remove the filter it does not refresh !

**Comment by h0jeZvgoxFepBQ2C** [comment]
same issue here, it doesn't work

**Comment by aminor00** [comment]
@jim-docker please can you re-open this ticket? The auto-refresh issue is still present in 2024 and wasn't fixed as you can see from comments in 2023.

CTRL-R doesn't seem to do a great job of refreshing either.  The only way to reliably refresh is to exit Lens and launch again.
