### ISSUE TITLE
OIDC does not work with custom CA

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#59]
**Describe the bug**
OIDC authentication does not work if `idp-issuer-url` uses custom CA.

**Logs:**

```
Invalid kubeconfig context test-cluster
AggregateError: RequestError: unable to verify the first certificate at ClientRequest.<anonymous> (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/got/index.js:182:22) RequestError: unable to verify the first certificate at ClientRequest.<anonymous>
```

**Kubeconfig:**

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://ucp:6443
  name: test-cluster
contexts:
- context:
    cluster: test-cluster
    user: me
  name: test-cluster
current-context: test-cluster
kind: Config
preferences: {}
users:
- name: me
  user:
    auth-provider:
      config:
        client-id: oidc
        client-secret: REDACTED
        id-token: REDACTED
        idp-issuer-url: https://ucp:32000
        refresh-token: REDACTED
      name: oidc
```

**Additional context**
This is probably a bug with ts/js kubernetes client library.

**Comment by jnummelin** [comment]
See upstream issue: https://github.com/kubernetes-client/javascript/issues/360

**Comment by jakolehm** [comment]
Fixed in 2.4.0.

**Comment by djgilcrease** [comment]
This is not fixed. I have v2.4.1 and I still see this issue

![image](https://user-images.githubusercontent.com/1778574/68147640-52b8ea80-feef-11e9-8474-5726c3ebae01.png)
